version: '3.8'

services:
  tgc-bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_REPO: https://github.com/moranmoa/TGC-bot.git
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      TOKEN: ${TOKEN}
      GUILD_ID: ${GUILD_ID}
      BOT_ID: ${BOT_ID}
      dev: ${dev}
      dudiBOT_ID: ${dudiBOT_ID}
      dudiTOKEN: ${dudiTOKEN}
      CLIENT_SECRET: ${CLIENT_SECRET}
      # נוסיף משתנה סביבה לפורט של השרת
      PORT: 8084 
    ports:
      # חשיפת הפורט מהקונטיינר של הבוט החוצה
      - "8084:8084" 
    volumes:
      - ./data:/app/data
    restart: always